### PR TITLE
compressed all jpg, png images and converted them into webp for better performance

### PR DESCRIPTION
**Pull request by Moamal-2000**
Hello @YieGin,

I liked your portfolio, keep up the good job man, I recently explored your portfolio and found it quite appealing. However, I noticed that the overall performance seems to be around 73%, and there were some instances of slow loading for animations and images. Considering that it's a Next.js app, I expected smoother performance.

I manually compressed all images and converted them into webp extension, but I couldn't run your website locally due to auth protection so I'm not sure if the paths of the images are set as they should be.

### CODE REVIEW

**Comment by YieGin** [comment]
I'm using image optimization it automatically handles this for me.

**Comment by YieGin** [comment]
I'm using image optimization; it automatically handles this for me.

**Comment by Moamal-2000** [comment]
For desktop it seems good, On mobile devices it went to 67%

Screenshot 2024-04-30 185937

Be careful, Each millisecond of the loading time is counted in this time, people don't want to wait more than 6 seconds even, I'm sure you don't want anyone who visite your portfolio to close it without even browsing the content due to loading time, At least compress these 2 images:

Screenshot 2024-04-30 185822
Screenshot 2024-04-30 185911

and convert them into webp format to improve your website loading time, Also there is an error in the console showing that there is a missing image probably the wrong path so make sure of it.

**Comment by YieGin** [comment]
Hello Moamal, thank you for your time and for trying to help me. However, sometimes AVIF can be better than WebP. Regarding performance, I'm not sure why yours is lower than 90% because mine is always above 90%. Here are images for both desktop and phone.
image1
image2

**Comment by Moamal-2000** [comment]
I rechecked the lighthouse analysis using incognito mode and got 85% and even if it was above 92% you still can improve it as you know because why not.
Screenshot 2024-05-01 114339

and the "best practice" score can be 100% if the path of your CV file is set correctly
Screenshot 2024-05-01 115032

Have a good day.

**Comment by YieGin** [comment]
Oh thanks i haven't seen this error about CV file it's fixed now.
image

**Pull request closed without merging**
